Homework 5
shivakcpm/ReactHomeTasks pull request #5
Opened 2020-09-25 07:32 UTC by shivakcpm

* Implemented movie details component
* Used react hooks wherever possible
* Migrated class components to functional components wherever is possible

2020-09-25 12:43 UTC, alionaSipchuk requested changes
Looks good) 
fix issues and let's create custom hook where will be filtered your movies by genre

2020-09-25 12:43 UTC, alionaSipchuk commented on src/components/MovieDetails/MovieDetailsComponent.js
> +          <img src="/public/searchIcon.PNG" onClick={props.goToHome.bind(this, null)} />
let's avoid bind in FC!!!!

2020-09-28 04:53 UTC, shivakcpm commented on src/components/App/App.js
> +          <ContentHolderComponent setMovieDetails= {setMovieDetails} allMovies={movies} setAllMovies= {setMovies} />
App component has componentholdercomponent , headercomponent, moviedetailscomponent has childrens. so these components can not communicate directly.

2020-10-12 07:30 UTC, alionaSipchuk approved these changes
Good job)

2020-10-12 07:30 UTC, alionaSipchuk commented on .eslintrc
> +      // "object-curly-spacing": [2, "always"],
remove comment

2020-10-12 07:30 UTC, alionaSipchuk commented on prettier.config.js
> +  // bracketSpacing: true,
ditto

2020-10-12 07:54 UTC, merged